# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a Docker image

on:
  push:
    branches: ['master']
  workflow_dispatch:
  schedule:
    # 6:05am Monday UTC; Sunday night local time
    - cron: "5 6 * * 1"

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set Environmental Variables
        run: |
          echo Repository: $REPOSITORY

          export IMAGE_NAME_2=${REPOSITORY//docker-/}
          export IMAGE_NAME=${IMAGE_NAME_2,,}
          echo Image Name: $IMAGE_NAME
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

          export VERSION=$(git describe --tags --always)
          echo Version: $VERSION
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

          export BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo Build Date: $BUILD_DATE
          echo "BUILD_DATE=${BUILD_DATE}" >> $GITHUB_ENV

          export DDNS_VERSION_X_Y_Z=$(cat ddns.py | grep -oP '__version__\s+=\s+\"?\K[\d\w\.]+')
          export DDNS_VERSION_X_Y=$(echo $DDNS_VERSION_X_Y_Z | cut -f 1-2 -d .)
          export DDNS_VERSION_X=$(echo $DDNS_VERSION_X_Y_Z | cut -f 1 -d .)
          echo Python Versions: ${DDNS_VERSION_X} ${DDNS_VERSION_X_Y} ${DDNS_VERSION_X_Y_Z}
          echo "DDNS_VERSION_X_Y_Z=${DDNS_VERSION_X_Y_Z}" >> $GITHUB_ENV
          echo "DDNS_VERSION_X_Y=${DDNS_VERSION_X_Y}" >> $GITHUB_ENV
          echo "DDNS_VERSION_X=${DDNS_VERSION_X}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the (GitHub) Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          build-args: |
            VERSION=${{ env.VERSION }}
            COMMIT=${{ github.sha }}
            URL=${{ github.repositoryUrl }}
            BRANCH=${{ github.ref_name }}
            BUILD_DATE=${{ env.BUILD_DATE }}
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DDNS_VERSION_X_Y_Z }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DDNS_VERSION_X_Y }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DDNS_VERSION_X }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
